set-option -g status-left-length 50
set-option -g mouse on
if-shell "uname -s | grep -q Darwin" \
    "set-option -s copy-command 'pbcopy'" \
    "set-option -s copy-command 'xclip -selection c'"
set-option -g default-terminal "tmux-256color"
set-option -a terminal-features "xterm-256color:RGB"
set-option -g focus-events on
set-option -g mode-keys vi
set -sg escape-time 10

# use ctrl-space as a second prefix key
set-option -g prefix2 C-Space

# make the messages shown by tmux stay forever until key is pressed
# https://unix.stackexchange.com/questions/339446/how-to-make-tmux-messages-stay-longer
set-option -g display-time 0

# automatically put sequencial number to windows so they are always arranged as 0, 1, 2, 3...
set-option -g renumber-windows on

# join panes and stack then horitontally
bind-key j command-prompt -p "join pane from:" "join-pane -h -s '%%'"

# use prefix + / to search from bottom to top right away, that's why reverse search (?) is used 
bind-key / copy-mode \; send-keys ?
# enable incremental search by default
bind-key -T copy-mode-vi / command-prompt -i -p "search down" "send -X search-forward-incremental \"%%%\""
bind-key -T copy-mode-vi ? command-prompt -i -p "search up" "send -X search-backward-incremental \"%%%\""

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
